import asyncio
from copy import deepcopy

from vbr_protocol.objects.groups import MemberState
from vbr_protocol.deserializers import deserialize_data
from vbr_protocol.objects.matchmaker import LayoutInfo
from accord_test_utils.helpers import account_key_for_email


from system_tests.test_groups import check_member_state_update
from system_tests.utils import send_arena_battle_results, get_arena_config, get_mm_config, \
    set_mm_config, create_game_client
from vbr_game_client import VBRGameClient as GameClient
from system_tests.test_groups import get_group_key_from_onlinelist

from system_tests.constants import (
    BR_EASY_AI_PRESET_NAME,
    BR_HARD_AI_PRESET_NAME,
    DEATHMATCH_PRESET_NAME,
    SPIES_PRESET_NAME,
)
from jazz_common import Message

# from vbr_protocol.messages.client.push.inventory import Update as InventoryPush


async def fetch_pushes(game_client: GameClient):
    while True:
        push = deserialize_data(await game_client.pushes.get())
        await game_client.on_push_received(push)
        print(f"Push received (client: {game_client.email}): {push}")


async def main():
    config_get = await get_mm_config()
    tmp_config = config_get
    for preset in tmp_config["presets"].values():
        preset["preserve_group"] = False
    await set_mm_config(tmp_config)
    async with create_game_client(email="testlogin1@test.iv") as game_client1:
        print("************Player1 Login**************")
        config = await game_client1.matchmaker.get_config_push()
        preset_config = config.presets[BR_HARD_AI_PRESET_NAME]
        preset_config.teams_layouts[1].layout = {
            BR_HARD_AI_PRESET_NAME: LayoutInfo(num_teams=3, team_size=4),
            SPIES_PRESET_NAME: LayoutInfo(num_teams=1, team_size=4)
        }
        preset_config.teams_layouts[0].weight = 1
        preset_config.teams_layouts[1].weight = 100
        await game_client1.matchmaker.update_preset(BR_HARD_AI_PRESET_NAME, preset_config)
        await asyncio.sleep(0.1)
        print("************ PRESET is Updated **************")
        fetch_pushes_task1 = asyncio.create_task(fetch_pushes(game_client1))
        await asyncio.sleep(1)
        async with create_game_client(email="testlogin2@test.iv") as game_client2:
            print("************Player2 Login**************")
            fetch_pushes_task2 = asyncio.create_task(fetch_pushes(game_client2))
            await asyncio.sleep(1)
            async with create_game_client(email="testlogin3@test.iv") as game_client3:
                print("************Player3 Login**************")
                fetch_pushes_task3 = asyncio.create_task(fetch_pushes(game_client3))
                await asyncio.sleep(1)
                async with create_game_client(email="testlogin4@test.iv") as game_client4:
                    print("************Player4 Login**************")
                    fetch_pushes_task4 = asyncio.create_task(fetch_pushes(game_client4))
                    await asyncio.sleep(1)
                    async with create_game_client(email="testlogin5@test.iv") as game_client5:
                        print("************Player5 Login**************")
                        fetch_pushes_task5 = asyncio.create_task(fetch_pushes(game_client5))
                        await asyncio.sleep(1)
                        print("************Player1 Create Group**************")
                        await game_client1.groups.create(b"group:group")
                        await asyncio.sleep(1)
                        print("****************** Change preset to SPIES ***************")
                        await game_client1.groups.update_preset_name(SPIES_PRESET_NAME)
                        await asyncio.sleep(0.5)
                        # print("************Player2 Create Group**************")
                        # await game_client2.groups.create(b"group2:group2")
                        # await asyncio.sleep(1)
                        # print("****************** Change preset to SPIES ***************")
                        # await game_client2.groups.update_preset_name(SPIES_PRESET_NAME)
                        # await asyncio.sleep(0.5)
                        print("************ Send Invite to Player3 **************")
                        await game_client1.groups.send_invite(game_client3.account_key)
                        await asyncio.sleep(0.5)
                        # print("************ Send Invite to Player5 **************")
                        # await game_client1.groups.send_invite(game_client5.account_key)
                        # await asyncio.sleep(0.5)
                        print("************ Player3 Accepts Invite **************")
                        await game_client3.groups.accept_invite(game_client1.account_key)
                        await asyncio.sleep(0.5)
                        # print("************ Player5 Accepts Invite **************")
                        # await game_client5.groups.accept_invite(game_client1.account_key)
                        # await asyncio.sleep(0.5)
                        print("*************** SET READY STATUS Player1 ***************")
                        await game_client1.groups.set_ready()
                        await asyncio.sleep(0.5)
                        print("*************** SET READY STATUS Player3 ***************")
                        await game_client3.groups.set_ready()
                        await asyncio.sleep(0.5)
                        # print("*************** SET READY STATUS Player5 ***************")
                        # await game_client5.groups.set_ready()
                        # await asyncio.sleep(0.5)
                        # print("************ Send Invite to Player4 **************")
                        # await game_client2.groups.send_invite(game_client4.account_key)
                        # await asyncio.sleep(0.5)
                        # print("************ Player4 Accepts Invite**************")
                        # await game_client4.groups.accept_invite(game_client2.account_key)
                        # await asyncio.sleep(0.5)
                        # print("*************** SET READY STATUS Player2 ***************")
                        # await game_client2.groups.set_ready()
                        # await asyncio.sleep(0.5)
                        # print("*************** SET READY STATUS Player4 ***************")
                        # await game_client4.groups.set_ready()
                        # await asyncio.sleep(0.5)
                        # print("************ Player1 Find BR_HARD **************")
                        # await game_client1.matchmaker.find_single_player_battle(BR_HARD_AI_PRESET_NAME)
                        # await asyncio.sleep(0.1)
                        print("************ Player2 Find BR_HARD **************")
                        await game_client2.matchmaker.find_single_player_battle(BR_HARD_AI_PRESET_NAME)
                        await asyncio.sleep(0.1)
                        print("************ Player5 Find SPIES **************")
                        await game_client5.matchmaker.find_single_player_battle(SPIES_PRESET_NAME)
                        await asyncio.sleep(0.5)
                        print("************ Player4 Find SPIES **************")
                        await game_client4.matchmaker.find_single_player_battle(BR_HARD_AI_PRESET_NAME)
                        await asyncio.sleep(1)
                        print("*************** Force Battle 1 ***************")
                        await game_client3.groups.force_battle(BR_HARD_AI_PRESET_NAME)
                        await asyncio.sleep(6)
                        # await game_client3.groups.leave()
                        # print("************ Player2 Find BR_HARD **************")
                        # await game_client2.matchmaker.find_single_player_battle(
                        #     BR_HARD_AI_PRESET_NAME)
                        # await asyncio.sleep(0.1)
                        # print("*************** SET READY STATUS Player1 ***************")
                        # await game_client1.groups.set_ready()
                        # await asyncio.sleep(0.5)
                        # print("*************** Force Battle 1 ***************")
                        # await game_client1.groups.force_battle(BR_HARD_AI_PRESET_NAME)
                        # await asyncio.sleep(6)
                        # print("*************** Force Battle 2 ***************")
                        # await game_client2.groups.force_battle(BR_HARD_AI_PRESET_NAME)
                        # await asyncio.sleep(6)
                        # print("************ Player2 Force Battle **************")
                        # await game_client2.matchmaker.force_battle(BR_HARD_AI_PRESET_NAME)
                        # await asyncio.sleep(6)
                        # print("************Send Invite to Player2**************")
                        # await game_client1.groups.send_invite(game_client2.account_key)
                        # await asyncio.sleep(2)
                        # print("************Send Invite to Player4**************")
                        # await game_client1.groups.send_invite(game_client4.account_key)
                        # await asyncio.sleep(2)
                        # print("************Player2 Accepts Invite **************")
                        # await game_client2.groups.accept_invite(game_client1.account_key)
                        # await asyncio.sleep(2)
                        # print("************Player4 Accepts Invite **************")
                        # await game_client4.groups.accept_invite(game_client1.account_key)
                        # await asyncio.sleep(3)
                        # print("***************SET READY STATUS Player2***************")
                        # await game_client2.groups.set_ready()
                        # await asyncio.sleep(2)
                        # print("***************SET READY STATUS Player4***************")
                        # await game_client4.groups.set_ready()
                        # await asyncio.sleep(2)
                        # print("************Player1 Leave Group**************")
                        # await game_client1.groups.leave()
                        # await asyncio.sleep(3)
                        # print("************Player3 Send Invite to Player1**************")
                        # await game_client3.groups.send_invite(game_client1.account_key)
                        # await asyncio.sleep(3)
                        # print("************Player3 Accepts Invite**************")
                        # await game_client1.groups.accept_invite(game_client3.account_key)
                        # print("************Player2 Create Group**************")
                        # await game_client2.groups.create(b"group2:group2")
                        # await asyncio.sleep(2)
                        # print("************Player2 Leave Group**************")
                        # await game_client2.groups.leave()
                        # await asyncio.sleep(3)
                        fetch_pushes_task1.cancel()
                        fetch_pushes_task2.cancel()
                        fetch_pushes_task3.cancel()
                        fetch_pushes_task4.cancel()
                        fetch_pushes_task5.cancel()
    await set_mm_config(config_get)
    await asyncio.sleep(1)


# async def main():
#     async with GameClient(email="testlogin1@test.iv", password="123456") as game_client1:
#         print("************Player1 Login**************")
#         fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client1))
#         await asyncio.sleep(1)
#         async with GameClient(email="testlogin2@test.iv", password="123456") as game_client2:
#             print("************Player2 Login**************")
#             fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client2))
#             await asyncio.sleep(1)
#             async with GameClient(email="testlogin3@test.iv", password="123456") as game_client3:
#                 print("************Player3 Login**************")
#                 fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client3))
#                 await asyncio.sleep(1)
#                 async with GameClient(email="testlogin4@test.iv",
#                                       password="123456") as game_client4:
#                     print("************Player4 Login**************")
#                     fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client4))
#                     await asyncio.sleep(1)
#                     print("************Player1 Create Group**************")
#                     await game_client1.groups.create(b"group:group")
#                     await asyncio.sleep(2)
#                     print("************Send Invite to Player3**************")
#                     await game_client1.groups.send_invite(game_client3.account_key)
#                     await asyncio.sleep(2)
#                     print("************Send Invite to Player2**************")
#                     await game_client1.groups.send_invite(game_client2.account_key)
#                     await asyncio.sleep(2)
#                     print("************Send Invite to Player4**************")
#                     await game_client1.groups.send_invite(game_client4.account_key)
#                     await asyncio.sleep(2)
#                     print("************Player3 Accepts Invite**************")
#                     await game_client3.groups.accept_invite(game_client1.account_key)
#                     await asyncio.sleep(2)
#                     print("******************Change MM_preset to Deathmatch2***************")
#                     await game_client1.groups.update_preset_name("Deathmatch2")
#                     await asyncio.sleep(1)
#                     print("************Player2 Accepts Invite **************")
#                     await game_client2.groups.accept_invite(game_client1.account_key)
#                     await asyncio.sleep(2)
#                     print("************Player4 Accepts Invite **************")
#                     await game_client4.groups.accept_invite(game_client1.account_key)
#                     await asyncio.sleep(3)
#                     print("***************SET READY STATUS Player1***************")
#                     await game_client1.groups.set_ready()
#                     await asyncio.sleep(2)
#                     print("***************SET READY STATUS Player2***************")
#                     await game_client2.groups.set_ready()
#                     await asyncio.sleep(2)
#                     print("***************SET READY STATUS Player3***************")
#                     await game_client3.groups.set_ready()
#                     await asyncio.sleep(2)
#                     print("***************SET READY STATUS Player4***************")
#                     await game_client4.groups.set_ready()
#                     await asyncio.sleep(2)
#                     # print("************Player1 Leave Group**************")
#                     # await game_client1.groups.leave()
#                     # await asyncio.sleep(3)
#                     # print("************Player3 Send Invite to Player1**************")
#                     # await game_client3.groups.send_invite(game_client1.account_key)
#                     # await asyncio.sleep(3)
#                     # print("************Player3 Accepts Invite**************")
#                     # await game_client1.groups.accept_invite(game_client3.account_key)
#                     # print("************Player2 Create Group**************")
#                     # await game_client2.groups.create(b"group2:group2")
#                     # await asyncio.sleep(2)
#                     # print("************Player2 Leave Group**************")
#                     # await game_client2.groups.leave()
#                     # await asyncio.sleep(3)
#                     fetch_pushes_task.cancel()
#     await asyncio.sleep(1)


            # group_key = await get_group_key_from_onlinelist(game_client2, game_client1)
            # await asyncio.sleep(2)
            # await game_client2.groups.join(group_key)
            # await asyncio.sleep(4)
            # fetch_pushes_task.cancel()


# async def main():
#     async with GameClient(email="testlogin8@test.iv", password="123456") as game_client:
#         fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client))
#         await asyncio.sleep(1)
#         # print("***********Get mm_config****************")
#         # mm_config = await get_mm_config()
#         # await asyncio.sleep(2)
#         # for preset in mm_config["presets"].values():
#         #     preset["preserve_group"] = False
#         # print("***********Set mm_config****************")
#         # await set_mm_config(mm_config)
#         # await asyncio.sleep(2)
#         # print("***********FIND BATTLE Deathmatch2****************")
#         # await game_client.matchmaker.find_single_player_battle("Deathmatch2")
#         # await asyncio.sleep(2)
#         print("**********CREATE GROUP*************")
#         await game_client.groups.create(b"group:group")
#         await asyncio.sleep(3)
#         print("**********CREATE GROUP*************")
#         await game_client.groups.create(b"")
#         await asyncio.sleep(3)
#         print("******************Change MM_preset to Deathmatch2***************")
#         await game_client.groups.update_preset_name("Deathmatch2")
#         await asyncio.sleep(1)
#         print("***************SET READY STATUS***************")
#         await game_client.groups.set_ready()
#         await asyncio.sleep(6)
#         fetch_pushes_task.cancel()
#         await asyncio.sleep(1)
#     await asyncio.sleep(3)


# async def main():
#     async with create_game_client(email="testlogin1@test.iv") as game_client1:
#         print("************Player1 Login**************")
#         fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client1))
#         await asyncio.sleep(1)
#         async with create_game_client(email="testlogin2@test.iv") as game_client2:
#             print("************Player2 Login**************")
#             fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client2))
#             await asyncio.sleep(1)
#             # async with GameClient(email="testlogin3@test.iv", password="123456") as game_client3:
#             #     print("************Player3 Login**************")
#             #     fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client3))
#             #     await asyncio.sleep(1)
#             print("************Player1 Create Group **************")
#             await game_client1.groups.create(b"group1:group1")
#             await asyncio.sleep(2)
#             print("************ Send Invite to Player2**************")
#             await game_client1.groups.send_invite(game_client2.account_key)
#             await asyncio.sleep(1.5)
#             print("************Player 2 Accepts Invite **************")
#             await game_client2.groups.accept_invite(game_client1.account_key)
#             await asyncio.sleep(2)
#         async with create_game_client(email="testlogin2@test.iv") as game_client2_recon:
#             print("************Player2 Login**************")
#             fetch_pushes_task = asyncio.create_task(fetch_pushes(game_client2_recon))
#             await asyncio.sleep(2)
            #await asyncio.sleep(1)
            #await asyncio.sleep(1.5)
            # print("***************SET READY STATUS Player1***************")
            # await game_client1.groups.set_ready()
            # await asyncio.sleep(1)
            # print("***************SET READY STATUS Player3***************")
            # await game_client2.groups.set_ready()
            # await asyncio.sleep(1)
            # print("******************Change MM_preset to Deathmatch2***************")
            # await game_client1.groups.update_preset_name("Deathmatch2")
            # await asyncio.sleep(1)

            # print("***************SET READY STATUS Player3***************")
            # await game_client3.groups.set_ready()
            # await asyncio.sleep(2)
            # print("************2 Send Invite to Player3**************")
            # await game_client2.groups.send_invite(game_client3.account_key)
            # await asyncio.sleep(1.5)

            # print("***********FIND BATTLE Deathmatch2****************")
            # await game_client1.matchmaker.find_single_player_battle("Deathmatch2")
            # await asyncio.sleep(3)
            # print("******************Change MM_preset to Deathmatch2***************")
            # await game_client1.groups.update_preset_name("Deathmatch2")
            # await asyncio.sleep(1)
            # print("***************SET READY STATUS Player1***************")
            # await game_client1.groups.set_ready()
            # await asyncio.sleep(2)
            # print("***************SET NOT READY STATUS Player1***************")
            # await game_client2.groups.set_not_ready()
            # await asyncio.sleep(2)
            # print("************Player2 LEAVE Group **************")
            # await game_client2.groups.leave()
            # await asyncio.sleep(4)
            # print("************Player2 Create Group 2**************")
            # await game_client2.groups.create(b"group2:group2")
            # await asyncio.sleep(2)
            # print("************Send Invite to Player3**************")
            # await game_client2.groups.send_invite(game_client3.account_key)
            # await asyncio.sleep(3)
            # print("************Player3 Accepts Invite from Player2**************")
            # await game_client3.groups.accept_invite(game_client2.account_key)
            # await asyncio.sleep(3)
            # print("************Rejeck invite 2**************")
            # await game_client2.groups.reject_invite(game_client1.account_key)
            # await asyncio.sleep(2)
            # print("************Revoke invite 2**************")
            # await game_client1.groups.revoke_invite(game_client2.account_key)
            # await asyncio.sleep(2)
            # print("************Player1 Close Client**************")
            # game_client1.close()
            # await asyncio.sleep(2)
            # print("************Send invite to Offline **************")
            # key = account_key_for_email("offline@rnd.wargaming.net")
            # await game_client1.groups.send_invite(key)
            # await asyncio.sleep(1.5)
            # print("************Player2 Join Group by Key **************")
            # group_key = await get_group_key_from_onlinelist(game_client2, game_client1)
            # await game_client2.groups.join(group_key)
            # await asyncio.sleep(2)
            # print("***************Force Battle***************")
            # await game_client1.groups.force_battle()
            # await asyncio.sleep(2)
    #         fetch_pushes_task.cancel()
    # await asyncio.sleep(1)


if __name__ == "__main__":
    asyncio.run(main())


